{{- $backendName := include "task-manager.fullnameSuffix" (dict "root" . "suffix" "backend") -}}
{{- $mysqlName := include "task-manager.fullnameSuffix" (dict "root" . "suffix" "mysql") -}}
{{- $mysqlSecret := printf "%s-secret" $mysqlName -}}
{{- $redisName := include "task-manager.fullnameSuffix" (dict "root" . "suffix" "redis") -}}
{{- $env := .Values.backend.env -}}
{{- $mysqlHost := default $mysqlName $env.MYSQL_HOST -}}
{{- $mysqlPort := default "3306" $env.MYSQL_PORT -}}
{{- $redisHost := default $redisName $env.REDIS_HOST -}}
{{- $redisPort := default "6379" $env.REDIS_PORT -}}
{{- $backendPort := default 5000 .Values.backend.service.port -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $backendName }}
  labels:
    {{- include "task-manager.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "task-manager.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "task-manager.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: {{ include "task-manager.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.28
          command: ["sh", "-c", "until nc -z {{ $mysqlName }} {{ $mysqlPort }}; do sleep 2; done;"]
        - name: wait-for-redis
          image: busybox:1.28
          command: ["sh", "-c", "until nc -z {{ $redisName }} {{ $redisPort }}; do sleep 2; done;"]
      containers:
        - name: backend
          image: {{ printf "%s:%s" .Values.backend.image.repository .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: MYSQL_HOST
              value: {{ $mysqlHost | quote }}
            - name: MYSQL_PORT
              value: {{ $mysqlPort | quote }}
            - name: MYSQL_USER
              value: {{ $env.MYSQL_USER | default "root" | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $mysqlSecret }}
                  key: mysql-password
            - name: MYSQL_DB
              value: {{ $env.MYSQL_DB | default "tasks_db" | quote }}
            - name: REDIS_HOST
              value: {{ $redisHost | quote }}
            - name: REDIS_PORT
              value: {{ $redisPort | quote }}
            - name: FE_HOST
              value: {{ $env.FE_HOST | default "localhost:8080" | quote }}
          ports:
            - name: http
              containerPort: {{ $backendPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ $backendPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ $backendPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- with .Values.backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}