{{- $frontendName := include "task-manager.fullnameSuffix" (dict "root" . "suffix" "frontend") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $frontendName }}
  labels:
    {{- include "task-manager.componentLabels" (dict "root" . "component" "frontend") | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "task-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
{{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
{{- end }}