{{- $mysqlName := include "task-manager.fullnameSuffix" (dict "root" . "suffix" "mysql") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $mysqlName }}
  labels:
    {{- include "task-manager.componentLabels" (dict "root" . "component" "mysql") | nindent 4 }}
spec:
  selector:
    {{- include "task-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql